//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int ID { get; set; }
        public long StdID { get; set; }
        public string name { get; set; }
        public string Field { get; set; }
        public System.DateTime Rtime { get; set; }
    }
}
