//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panel_Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DrZinoV2Entities : DbContext
    {
        public DrZinoV2Entities()
            : base("name=DrZinoV2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DisaseQuestion> DisaseQuestions { get; set; }
        public virtual DbSet<Disease> Diseases { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
    }
}
