//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Mes_ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public string MSG { get; set; }
        public string Time_ { get; set; }
        public string Date_ { get; set; }
        public Nullable<int> Type_ { get; set; }
    }
}
